spring.application.name=api-techvault
spring.datasource.url=conexion
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080